project:
  name: bach-application-template
  description: Modular Java Application Template
  website: https://github.com/sormuras/bach-application-template
  authors:
    - Christian Stein
  license: https://choosealicense.com

release:
  github:
    owner: sormuras
    overwrite: true

files:
  artifacts:
    - path: artifact/bach-application-template-{{projectVersion}}-Linux.zip
    - path: artifact/bach-application-template-{{projectVersion}}-macOS.zip
    - path: artifact/bach-application-template-{{projectVersion}}-Windows.zip
