name: release

on:
  workflow_dispatch:
    inputs:
      tag-version:
        description: 'Tag as version'
        required: true
        default: '1-ea'
      pre-release:
        description: 'Pre-release? [true|false]'
        required: true
        default: 'true'

env:
  VERSION: ${{ github.event.inputs.tag-version }}

jobs:
  build:
    name: 'Build with Java ${{ matrix.java }} on ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , macOS-latest, windows-latest ]
        java: [ 16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: 'Build with Bach'
        uses: sormuras/bach-build@v1
        with:
          bach-arguments: --project-version ${{ env.VERSION }} build
      - name: 'Upload build artifact'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ env.VERSION }}-${{ runner.os }}
          path: |
            .gitignore
            .bach/workspace/logbook.md
            .bach/workspace/image
  deploy-to-releases:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Download all build artifacts'
        uses: actions/download-artifact@v2
      - name: 'Display structure of downloaded files'
        run: ls -R
